### ISSUE TITLE
Plot Temporal/Taxonomic Consistency for Epsilon = x; Error: object 'values' not found.

### ISSUE THREAD

**Issue by fwhelan** [beiko-lab/ananke-ui#1]
Upon choosing eps in the Explore Clusters panel, then returning to the Data Summary panel, I receive an error when I click to "Plot Temporal/Taxonomic Consistency for Epsilon = x" of `Error: object 'values' not found.` This appears to happen for any value of eps. The output to the R shell when this occurs is 

```
Warning: Error in eval: object 'values' not found
Stack trace (innermost first):
    70: output$temptaxconsist
     3: runApp
     2: runUrl
     1: runGitHub
```

**Comment by fwhelan** [comment]
```
> sessionInfo()
R version 3.2.2 (2015-08-14)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.9.5 (Mavericks)
```

**Comment by mwhall** [comment]
ggplot doesn't want to plot the dataframe, possibly because it's empty. Are your taxonomic classifications loaded into the data file? What do they look like in the data tables on the Explore Clusters tab? It's coded to deal with GreenGenes style (i.e., 7 levels, semi-colon separated, beginning with k__, p__, c__, etc.). Any other style will have to be coded in.

**Comment by fwhelan** [comment]
Sorry, this was my fault!
